[[Qdrant]]
arch = "aarch64"
git-tree-sha1 = "4723e58b38444b55f838cb4d134708e561c9d3f7"
os = "macos"

    [[Qdrant.download]]
    sha256 = "ec3716a0b26c9feda47c1f8e03a43a3bb12e0bb50da5d611a53df390eca7fe5c"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.17.1+0/Qdrant.v1.17.1.aarch64-apple-darwin.tar.gz"
[[Qdrant]]
arch = "aarch64"
git-tree-sha1 = "c29f7c58632c52c87e03f110f23a0531e788a09a"
libc = "musl"
os = "linux"

    [[Qdrant.download]]
    sha256 = "789c1df8f4a224efb378e2d4462941228026e37c285c512fb87fadfb2736b4fc"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.17.1+0/Qdrant.v1.17.1.aarch64-linux-musl.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "698b5f6bca8e3bca14c5516e3cc121ff9c5fcfad"
os = "macos"

    [[Qdrant.download]]
    sha256 = "639abe5fc1a28ed614e9feebcc467e1b9bda2ece84808c5e4c4c390b1d06c1c6"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.17.1+0/Qdrant.v1.17.1.x86_64-apple-darwin.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "272d4e6303a9ea651a96ddaf5d38656fb3006fcb"
libc = "glibc"
os = "linux"

    [[Qdrant.download]]
    sha256 = "8670fec59fa9528bf8dd712e68c461919e0d3a9bab20d81a32af58cd4e74d693"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.17.1+0/Qdrant.v1.17.1.x86_64-linux-gnu.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "85449642b48381d558546356eebaa6abde3e706d"
libc = "musl"
os = "linux"

    [[Qdrant.download]]
    sha256 = "c157eb0125273db158c5a91d379c7923091ec71e27f09e8572c9f30ed2ff7534"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.17.1+0/Qdrant.v1.17.1.x86_64-linux-musl.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "1df3078034d9e2b19742625fc2940a854fca046b"
os = "windows"

    [[Qdrant.download]]
    sha256 = "9d23b37b8af5e8deb7bae852def32a8e16baaedf55e74225dc00decfcb1816b5"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.17.1+0/Qdrant.v1.17.1.x86_64-w64-mingw32.tar.gz"
