[[Qdrant]]
arch = "aarch64"
git-tree-sha1 = "0b3c4e76cc1a5180e718b542e7e536c7e938512c"
os = "macos"

    [[Qdrant.download]]
    sha256 = "58ce5e3f68dadd48103cc0f69a9f9027729a6081f884466c4f7bb666f28e1c98"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.18.3+0/Qdrant.v1.18.3.aarch64-apple-darwin.tar.gz"
[[Qdrant]]
arch = "aarch64"
git-tree-sha1 = "f0fb0ab2b2b91f7b02b0e0d2215ddedaf5e6b760"
libc = "musl"
os = "linux"

    [[Qdrant.download]]
    sha256 = "8a1c51217b529a55a3f0f58992d61271db55973e87a88afadc276fb3e9b7b373"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.18.3+0/Qdrant.v1.18.3.aarch64-linux-musl.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "8879e873e8ae9e63f3db4eb0eef1b6402b14b0e2"
os = "macos"

    [[Qdrant.download]]
    sha256 = "7436a6526d2d97806623a616965c7b3323110eaa00c134bcca5aa79f5715f707"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.18.3+0/Qdrant.v1.18.3.x86_64-apple-darwin.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "d3ca44405833f949528afc9f9fff5b3828b4ce6a"
libc = "glibc"
os = "linux"

    [[Qdrant.download]]
    sha256 = "e5c1cf1807e741dac07d97c08f81be8240763d81335e4e0ba99d0444a7f5968b"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.18.3+0/Qdrant.v1.18.3.x86_64-linux-gnu.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "abcde6d3b448f76ee3d7652ddbe1199b7e8c482d"
libc = "musl"
os = "linux"

    [[Qdrant.download]]
    sha256 = "7c52d606ff05a41078884d4b47aad6b2fa17dd6062ce7c726e1bf2dca77c3a11"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.18.3+0/Qdrant.v1.18.3.x86_64-linux-musl.tar.gz"
[[Qdrant]]
arch = "x86_64"
git-tree-sha1 = "8ebb3311f17e6c6eeec47f071e75496f84c72c0d"
os = "windows"

    [[Qdrant.download]]
    sha256 = "045b530dfec1b32e1877072623ee49eafa63f5bc4fea99d3708b20af093f14df"
    url = "https://github.com/JuliaBinaryWrappers/Qdrant_jll.jl/releases/download/Qdrant-v1.18.3+0/Qdrant.v1.18.3.x86_64-w64-mingw32.tar.gz"
