# Autogenerated wrapper script for Qdrant_jll for aarch64-apple-darwin
export qdrant

JLLWrappers.@generate_wrapper_header("Qdrant")
JLLWrappers.@declare_executable_product(qdrant)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        qdrant,
        "bin/qdrant",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
